name: Shell Commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echoes a string
        run: echo "Hello World 02"
      - name: multiline script example
        run:  |
          node -v
          npm -v
      - name: python Command
        run:  |
          import platform
          print(platform.processor())
        shell: python